# Generated by Django 4.2.17 on 2025-01-03 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='executer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exe_name', models.CharField(max_length=200, null=True)),
                ('exe_post', models.CharField(max_length=200, null=True)),
                ('exe_code', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
