# Generated by Django 5.1.4 on 2025-01-04 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='executer_code',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
