# Generated by Django 5.1.4 on 2025-01-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0003_task_executer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='enddate_store',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='startdate_store',
            field=models.DateField(null=True),
        ),
    ]
