# Generated by Django 5.1.4 on 2025-01-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0004_task_enddate_store_task_startdate_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='remain_date',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
