# Generated by Django 5.1.4 on 2025-01-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0005_task_remain_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='taskprogress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executer', models.CharField(max_length=200, null=True)),
                ('executer_code', models.CharField(max_length=200, null=True)),
                ('startdate', models.CharField(max_length=200, null=True)),
                ('remain_date', models.IntegerField(default=0, null=True)),
                ('enddate', models.CharField(max_length=100, null=True)),
                ('finishdate', models.CharField(max_length=100, null=True)),
                ('pariority', models.CharField(max_length=100, null=True)),
                ('task_sub', models.CharField(max_length=100, null=True)),
                ('task_desc', models.TextField(null=True)),
                ('enterydate', models.CharField(max_length=200, null=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
