# Generated by Django 5.1.4 on 2025-01-06 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0006_taskprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='taskcode',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
