# Generated by Django 5.1.4 on 2025-01-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0007_taskprogress_taskcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='system_code',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
