# Generated by Django 5.1.4 on 2025-01-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0008_task_system_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='preiod',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
