# Generated by Django 5.1.4 on 2025-01-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0009_taskprogress_preiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
