# Generated by Django 5.1.4 on 2025-01-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0010_task_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskprogress',
            name='progress',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
