# Generated by Django 5.1.4 on 2025-01-12 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleapp', '0014_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='task_id',
        ),
    ]
